openapi: "3.0.2"
info:
  title: Message Board API
  version: "1.0"
components:
  securitySchemes:
    basicAuth:
      type: http
      schema: basic
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
    TooManyRequests:
      description: Too many requests
  schemas:
    message:
      type: object
      description: A message
      required:
        - name
        - msg
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 10
          pattern: "[A-Za-z]{2,}"
          description: |
            Name of User who created
            the message.
          example: Fred
        msg:
          type: string
          minLength: 3
          maxLength: 20
          example: Hello World!
    user:
      type: object
      description: an user
      required: 
        - email
        - username
        - password
      properties:
        username:
          type: string
          minLength: 2
          maxLength: 10
          pattern: "[A-Za-z]{2,}"
          description: Name of an user
          example: jameschoi
        email:
          type: string
          format: email
          description: e-mail address
          example: ics012@camosun.bc.ca
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 64
          description: credential for login
          example: p@ssword!
paths: 
  /messages:
    description: All the messages
    get:
      summary: List all the messages
      description: |
        List all the messages in the order
        they were posted (newest at top)
      responses:
        "200":
           description: All the messages 
           content:
             application/json:
               schema:
                 type: array
                 items:
                   $ref: "#/components/schemas/message" 
        "400":
          description: Bad Request
        "429":
          $ref: "#/components/responses/TooManyRequests"
    post:
      security:
        - basicAuth: []
      summary: Add a new messages
      description: |
        Add new message
      requestBody:
        description: Message's data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
      responses:
        "201":
          description: New message posted 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message"
        "400":
          description: Bad Request. The message is the body of the Request is either missing or malformed.
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "429":
          $ref: "#/components/responses/TooManyRequests"
  /users:
    description: All Users
    post:
      summary: Add a new user
      description: |
        Add a new user
      requestBody: 
        description: User's data
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "201":
          description: New user added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          description: Bad Request. The user information is the body of the Request is either missing or malformed.
        "403": 
          description: Forbiden. Username or email already exists.
        "429":
          description: Too Many Requests

  