openapi: "3.0.2"
info:
  title: Message Board API
  version: "1.0"
components:
  schemas:
    message:
      type: object
      description: A message
      required:
        - name
        - msg
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 10
          pattern: "[A-Za-z]{2,}"
          description: |
            Name of User who created
            the message.
          example: Fred
        msg:
          type: string
          minLength: 3
          maxLength: 20
          example: Hello World!
paths: 
  /messages:
    description: All the messages
    get:
      summary: List all the messages
      description: |
        List all the messages in the order
        they were posted (newest at top)
      responses:
        "200":
           description: All the messages 
           content:
             application/json:
               schema:
                 type: array
                 items:
                   $ref: "#/components/schemas/message" 
        "400":
          description: Bad Request
    post:
      summary: List all the messages
      description: |
        List all the messages in the order
        they were posted (newest at top)
      requestBody:
        description: Message's data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
      responses:
        "201":
          description: All the messages 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message"
        "400":
          description: Bad Request. The message is the body of the Request is either missing or malformed.
          
